name: ci
on: [push, pull_request]
jobs:
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.1", "8.2"]
        composer_command: ["composer install", "composer update --prefer-lowest"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: docker-compose exec -T web composer self-update # Fix for broken GitHub pipeline.
      - name: build
        run: docker-compose exec -T web ${{ matrix.composer_command }}
      - name: test
        run: docker-compose exec -T web ./vendor/bin/phpunit
  code-sniffer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.1", "8.2"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: docker-compose exec -T web composer self-update # Fix for broken GitHub pipeline.
      - name: build
        run: docker-compose exec -T web composer install
      - name: test
        run: docker-compose exec -T web ./vendor/bin/grumphp run